apiVersion: apps/v1
kind: Deployment
metadata:
  name: prr-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prr-service
  template:
    metadata:
      labels:
        app: prr-service
    spec:
      containers:
      - name: prr-service
        image: ghcr.io/adiilkwz/sre-capstone-project/dummy-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "128Mi"