apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prr-app-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prr-service
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: web
    path: /metrics
    interval: 15s