apiVersion: v1
kind: Service
metadata:
  name: prr-app-service
  labels:
    app: prr-service
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: prr-service